<?php

/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/12/13
 * Time: 14:44
 */
namespace app\index\validate;


use think\Validate;

class PkUserVal extends Validate
{
//   public function rule($name, $rule = '')
//   {
//       return parent::rule($name, $rule); // TODO: Change the autogenerated stub
//   }

    protected  $rule = [
            'phone'   => 'require|number',//手机号
            'plate' => ['regex'=>'/[京津沪渝冀豫云辽黑湘皖鲁新苏浙赣鄂桂甘晋蒙陕吉闽贵粤青藏川宁琼使领A-Z]{1}[A-Z]{1}[A-Z0-9]{4}[A-Z0-9挂学警港澳]{1}/'],//车牌号
        ];
    protected  $msg = [
            'phone.require' => '手机号必须填写',
            'phone.number'     => '手机号格式有误',
            'plate'   => '车牌号有误',
        ];
//        $validate = new Validate($rule, $msg);


}